import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createAuthServerClient } from "../../../../lib/supabase-auth/server";
export const dynamic = "force-dynamic";
type PageProps = { params: Promise<{ id: string }> };
type Item = { product_name: string; product_price: number; quantity: number };
const money = (v: number) => Number(v || 0).toLocaleString("vi-VN") + "₫";
const date = (v: string) => new Date(v).toLocaleString("vi-VN");
export default async function OrderDetail({ params }: PageProps) {
  const { id } = await params; const supabase = await createAuthServerClient(); const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect(`/dang-nhap?next=/tai-khoan/don-hang/${encodeURIComponent(id)}`);
  const { data: order } = await supabase.from("orders").select("id,customer_name,customer_phone,customer_email,customer_address,note,payment_method,payment_status,status,subtotal,shipping_fee,total,created_at,order_items(product_name,product_price,quantity)").eq("id", id).eq("customer_id", user.id).maybeSingle();
  if (!order) notFound(); const items = (order.order_items || []) as Item[];
  return <section className="detail"><Link className="back" href="/tai-khoan/don-hang">← Quay lại đơn hàng</Link><header><p>ORDER DETAIL</p><h1>Đơn #{order.id.slice(0,8).toUpperCase()}</h1><span>Đặt lúc {date(order.created_at)}</span></header><div className="status"><div><small>Trạng thái đơn</small><b>{order.status}</b></div><div><small>Thanh toán</small><b>{order.payment_method === "cod" ? "COD" : "VNPAY / QR"}</b></div><div><small>Tình trạng thanh toán</small><b>{order.payment_status || "Đang cập nhật"}</b></div></div><div className="grid"><article><h2>Sản phẩm đã mua</h2>{items.map((item,i)=><div className="item" key={`${item.product_name}-${i}`}><div><b>{item.product_name}</b><span>{item.quantity} × {money(item.product_price)}</span></div><strong>{money(item.quantity*item.product_price)}</strong></div>)}<div className="totals"><div><span>Tạm tính</span><b>{money(order.subtotal)}</b></div><div><span>Phí vận chuyển</span><b>{order.shipping_fee === 0 ? "Miễn phí" : money(order.shipping_fee)}</b></div><div className="total"><span>Tổng cộng</span><b>{money(order.total)}</b></div></div></article><article><h2>Thông tin nhận hàng</h2><div className="info"><label>Người nhận</label><p>{order.customer_name}</p><label>Số điện thoại</label><p>{order.customer_phone}</p><label>Email</label><p>{order.customer_email || "Không có"}</p><label>Địa chỉ</label><p>{order.customer_address}</p>{order.note && <><label>Ghi chú</label><p>{order.note}</p></>}</div></article></div><style>{`
    .back{display:inline-flex;margin-bottom:30px;color:#00e5ff;text-decoration:none;font-weight:850}header p{margin:0 0 10px;color:#00e5ff;font-size:12px;font-weight:950;letter-spacing:2px}header h1{margin:0 0 9px;font-size:41px}header span{color:#9eadd3}.status{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin:31px 0 22px}.status div,article{padding:22px;border-radius:18px;border:1px solid rgba(0,229,255,.16);background:rgba(255,255,255,.055)}.status small{display:block;color:#92a4cf;margin-bottom:10px}.status b{color:#00e5ff}.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}article h2{margin:0 0 19px;font-size:22px}.item{display:flex;justify-content:space-between;gap:15px;padding:16px 0;border-bottom:1px solid rgba(255,255,255,.1)}.item b{display:block;margin-bottom:7px}.item span{color:#9eadd3}.item strong{color:#ff78d2}.totals{display:grid;gap:13px;margin-top:21px}.totals div{display:flex;justify-content:space-between}.totals .total{padding-top:15px;border-top:1px solid rgba(255,255,255,.13);font-size:21px}.totals .total b{color:#00e5ff}.info label{display:block;color:#92a4cf;font-size:13px;margin-bottom:6px}.info p{margin:0 0 19px;line-height:1.55}@media(max-width:900px){.status,.grid{grid-template-columns:1fr}}
  `}</style></section>;
}
