import Link from "next/link";
import { redirect } from "next/navigation";
import { createAuthServerClient } from "../../../lib/supabase-auth/server";
export const dynamic = "force-dynamic";
type OrderItem = { quantity: number };
type Order = { id: string; total: number; status: string; payment_method: string; payment_status: string | null; created_at: string; order_items: OrderItem[] | null };
const money = (v: number) => Number(v || 0).toLocaleString("vi-VN") + "â‚«";
const date = (v: string) => new Date(v).toLocaleString("vi-VN");
function badge(status: string) { return ["HoÃ n thÃ nh", "ÄÃ£ thanh toÃ¡n"].includes(status) ? "success" : ["ÄÃ£ há»§y", "Thanh toÃ¡n tháº¥t báº¡i"].includes(status) ? "danger" : "pending"; }
export default async function CustomerOrdersPage() {
  const supabase = await createAuthServerClient(); const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/dang-nhap?next=/tai-khoan/don-hang");
  const { data, error } = await supabase.from("orders").select("id,total,status,payment_method,payment_status,created_at,order_items(quantity)").or(`customer_id.eq.${user.id},customer_email.eq.${user.email || ""}`).order("created_at", { ascending: false });
  const orders = (data || []) as Order[];
  return <section className="orders"><header><p>MY ORDERS</p><h1>ÄÆ¡n hÃ ng cá»§a tÃ´i</h1><span>Theo dÃµi cÃ¡c Ä‘Æ¡n Ä‘Æ°á»£c thanh toÃ¡n báº±ng tÃ i khoáº£n nÃ y.</span></header>{error ? <div className="empty">KhÃ´ng táº£i Ä‘Æ°á»£c Ä‘Æ¡n hÃ ng. Vui lÃ²ng thá»­ láº¡i.</div> : !orders.length ? <div className="empty"><h2>Báº¡n chÆ°a cÃ³ Ä‘Æ¡n hÃ ng nÃ o</h2><p>Chá»n máº«u mÃ´ hÃ¬nh yÃªu thÃ­ch rá»“i thanh toÃ¡n Ä‘á»ƒ Ä‘Æ¡n xuáº¥t hiá»‡n á»Ÿ Ä‘Ã¢y.</p><Link href="/products">Xem sáº£n pháº©m</Link></div> : <div className="list">{orders.map(order => <Link className="card" key={order.id} href={`/tai-khoan/don-hang/${order.id}`}><div><b className="code">#{order.id.slice(0,8).toUpperCase()}</b><small>{date(order.created_at)}</small></div><div><small>Sáº£n pháº©m</small><b>{(order.order_items || []).reduce((sum,item)=>sum+Number(item.quantity),0)} mÃ³n</b></div><div><small>Thanh toÃ¡n</small><b>{order.payment_method === "cod" ? "COD" : "VNPAY"}</b></div><div><small>Tá»•ng tiá»n</small><b className="price">{money(order.total)}</b></div><span className={`badge ${badge(order.status)}`}>{order.status}</span></Link>)}</div>}<style>{`
    header p{margin:0 0 10px;color:#00e5ff;font-size:12px;font-weight:950;letter-spacing:2px}header h1{margin:0 0 10px;font-size:42px}header span{color:#aab9dd}.list{display:grid;gap:14px;margin-top:34px}.card{display:grid;grid-template-columns:minmax(180px,1.4fr) repeat(3,minmax(110px,1fr)) auto;gap:16px;align-items:center;padding:21px;border-radius:18px;border:1px solid rgba(0,229,255,.16);background:rgba(255,255,255,.055);color:#fff;text-decoration:none}.card:hover{border-color:rgba(0,229,255,.45)}.card small{display:block;color:#92a4cf;margin-bottom:7px}.code{display:block;margin-bottom:7px;color:#00e5ff}.price{color:#ff78d2}.badge{padding:8px 12px;border-radius:999px;font-size:12px;font-weight:900}.success{color:#50efa0;background:rgba(37,194,110,.15)}.pending{color:#ffd36e;background:rgba(255,184,52,.14)}.danger{color:#ff96a5;background:rgba(255,75,100,.14)}.empty{margin-top:34px;padding:42px;border-radius:20px;background:rgba(255,255,255,.05);border:1px solid rgba(0,229,255,.16);text-align:center;color:#aab9dd}.empty h2{color:#fff}.empty a{display:inline-flex;margin-top:18px;padding:13px 20px;border-radius:12px;color:#061020;font-weight:950;text-decoration:none;background:linear-gradient(135deg,#7c4dff,#00e5ff)}@media(max-width:950px){.card{grid-template-columns:1fr 1fr}}
  `}</style></section>;
}
